export const GET_CALENDAR_LIST_BEGIN = 'GET_CALENDAR_LIST_BEGIN';
export const GET_CALENDAR_LIST_SUCCESS = 'GET_CALENDAR_LIST_SUCCESS';
export const GET_CALENDAR_LIST_FAILURE = 'GET_CALENDAR_LIST_FAILURE';

export const POST_CALENDAR_LIST_BEGIN = 'POST_CALENDAR_LIST_BEGIN';
export const POST_CALENDAR_LIST_SUCCESS = 'POST_CALENDAR_LIST_SUCCESS';
export const POST_CALENDAR_LIST_FAILURE = 'POST_CALENDAR_LIST_FAILURE';

export const MOVE_CALENDAR_LIST_BEGIN = 'BEGIN_MOVE_CALENDAR_LIST';
export const MOVE_CALENDAR_LIST_SUCCESS = 'MOVE_CALENDAR_LIST_SUCCESS';
export const MOVE_CALENDAR_LIST_FAILURE = 'MOVE_CALENDAR_LIST_FAILURE';

export const EDIT_CALENDAR_LIST_BEGIN = 'EDIT_CALENDAR_LIST_BEGIN';
export const EDIT_CALENDAR_LIST_SUCCESS = 'EDIT_CALENDAR_LIST_SUCCESS';
export const EDIT_CALENDAR_LIST_FAILURE = 'EDIT_CALENDAR_LIST_FAILURE';

export const QUICK_ADD_CALENDAR_LIST_BEGIN = 'QUICK_ADD_CALENDAR_LIST_BEGIN';
export const QUICK_ADD_CALENDAR_LIST_SUCCESS = 'QUICK_ADD_CALENDAR_LIST_SUCCESS';
export const QUICK_ADD_CALENDAR_LIST_FAILURE = 'QUICK_ADD_CALENDAR_LIST_FAILURE';

export const UPDATE_CALENDAR_LISTS_BEGIN = 'UPDATE_CALENDAR_LISTS_BEGIN';
export const UPDATE_CALENDAR_LISTS_SUCCESS = 'UPDATE_CALENDAR_LISTS_SUCCESS';
export const UPDATE_CALENDAR_LISTS_FAILURE = 'UPDATE_CALENDAR_LISTS_FAILURE';

export const DELETE_CALENDAR_LIST_BEGIN = 'DELETE_CALENDAR_LIST';
export const DELETE_CALENDAR_LIST_SUCCESS = 'DELETE_CALENDAR_LIST_SUCCESS';
export const DELETE_CALENDAR_LIST_FAILURE = 'DELETE_CALENDAR_LIST_FAILURE';
