export const GET_CALENDAR_BEGIN = 'GET_CALENDAR_BEGIN';
export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS';
export const GET_CALENDAR_FAILURE = 'GET_CALENDAR_FAILURE';

export const POST_CALENDAR_BEGIN = 'POST_CALENDAR_BEGIN';
export const POST_CALENDAR_SUCCESS = 'POST_CALENDAR_SUCCESS';
export const POST_CALENDAR_FAILURE = 'POST_CALENDAR_FAILURE';

export const MOVE_CALENDAR_BEGIN = 'BEGIN_MOVE_CALENDAR';
export const MOVE_CALENDAR_SUCCESS = 'MOVE_CALENDAR_SUCCESS';
export const MOVE_CALENDAR_FAILURE = 'MOVE_CALENDAR_FAILURE';

export const EDIT_CALENDAR_BEGIN = 'EDIT_CALENDAR_BEGIN';
export const EDIT_CALENDAR_SUCCESS = 'EDIT_CALENDAR_SUCCESS';
export const EDIT_CALENDAR_FAILURE = 'EDIT_CALENDAR_FAILURE';

export const QUICK_ADD_CALENDAR_BEGIN = 'QUICK_ADD_CALENDAR_BEGIN';
export const QUICK_ADD_CALENDAR_SUCCESS = 'QUICK_ADD_CALENDAR_SUCCESS';
export const QUICK_ADD_CALENDAR_FAILURE = 'QUICK_ADD_CALENDAR_FAILURE';

export const UPDATE_CALENDARS_BEGIN = 'UPDATE_CALENDARS_BEGIN';
export const UPDATE_CALENDARS_SUCCESS = 'UPDATE_CALENDARS_SUCCESS';
export const UPDATE_CALENDARS_FAILURE = 'UPDATE_CALENDARS_FAILURE';

export const DELETE_CALENDAR_BEGIN = 'DELETE_CALENDAR';
export const DELETE_CALENDAR_SUCCESS = 'DELETE_CALENDAR_SUCCESS';
export const DELETE_CALENDAR_FAILURE = 'DELETE_CALENDAR_FAILURE';
